version: '3.1'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}
    
volumes:
  mongo:
    driver: ${VOLUMES_DRIVER}

services:

### MongoDB ##############################################
  mongo:
    build: ./mongo
    container_name: mongodb
    ports:
      - "${MONGODB_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    volumes:
      - ${DATA_PATH_HOST}/mongo:/data/db
      - ${DATA_PATH_HOST}/mongo_config:/data/configdb
      - ${MONGO_CREATE_USER}:/docker-entrypoint-initdb.d/mongo-init.js
    networks:
      - backend